"""add postlike/replylike/activity table

Revision ID: a53dceb3313b
Revises: 83fb73085bcf
Create Date: 2024-05-18 15:53:54.083248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53dceb3313b'
down_revision = '83fb73085bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
